-- Add sugar tracking fields to nutrition-bearing tables.
ALTER TABLE "NutritionGoal" ADD COLUMN "sugarG" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "FoodItem" ADD COLUMN "sugarPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "DiaryEntry" ADD COLUMN "sugarG" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SavedMealItem" ADD COLUMN "sugarG" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Recipe" ADD COLUMN "sugarG" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Recipe" ADD COLUMN "perServingSugarG" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "RecipeIngredient" ADD COLUMN "sugarG" DOUBLE PRECISION NOT NULL DEFAULT 0;
